[package]
name = "noggin"
version = "0.1.0"
edition = "2021"

[dependencies]
#noggin-derive = "0.1.0"
#noggin-parser = "0.1.0"
noggin-derive = { path = "../noggin-derive" }
noggin-parser = { path = "../noggin-parser" }

[dev-dependencies]
rstest = { workspace = true }
